
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TemplateManagementSystem.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class BussinessQuotesViewModel
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BussinessQuotesViewModel()
    {

        this.bussinessQuotesItems = new HashSet<bussinessQuotesItem>();

    }


    public int Id { get; set; }

    public string Email { get; set; }

    public string Subject { get; set; }

    public string CC { get; set; }

    public string EmailBody { get; set; }

    public System.DateTime expirydate { get; set; }

    public System.DateTime issuedate { get; set; }

    public string quoteTxt { get; set; }

    public System.DateTime ecd { get; set; }

    public System.DateTime ecod { get; set; }

    public string address1 { get; set; }

    public string address2 { get; set; }

    public string Name { get; set; }

    public string phone { get; set; }

    public string type { get; set; }

    public decimal subtotall { get; set; }

    public decimal discount { get; set; }

    public decimal totallTaxAmount { get; set; }

    public decimal shipingHandling { get; set; }

    public decimal tax { get; set; }

    public decimal totall { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public System.DateTime createdAt { get; set; }

    public string Filename { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<bussinessQuotesItem> bussinessQuotesItems { get; set; }

}

}
