
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TemplateManagementSystem.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class customerItem
{

    public int id { get; set; }

    public string service { get; set; }

    public int quantity { get; set; }

    public decimal price { get; set; }

    public decimal totall { get; set; }

    public Nullable<int> CustomerTempleteModel_Id { get; set; }

    public string decription { get; set; }



    public virtual CustomerTempleteModel CustomerTempleteModel { get; set; }

}

}
