
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TemplateManagementSystem.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class PressureWashingViewModel
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PressureWashingViewModel()
    {

        this.WashingTempletItems = new HashSet<WashingTempletItem>();

    }


    public int Id { get; set; }

    public string Email { get; set; }

    public string Subject { get; set; }

    public string CC { get; set; }

    public string EmailBody { get; set; }

    public System.DateTime date { get; set; }

    public string InvoiceId { get; set; }

    public string For { get; set; }

    public string Address { get; set; }

    public string type { get; set; }

    public string Notes { get; set; }

    public string PreparedBy { get; set; }

    public decimal subtotall { get; set; }

    public decimal tax { get; set; }

    public decimal totall { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime createdAt { get; set; }

    public string Filename { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public string userProfile { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WashingTempletItem> WashingTempletItems { get; set; }

}

}
