
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TemplateManagementSystem.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class SubscriptionModel
{

    public int id { get; set; }

    public string AppUserId { get; set; }

    public string GoCardlessId { get; set; }

    public string AccountHoldername { get; set; }

    public string PlanName { get; set; }

    public string AccountNo { get; set; }

    public string BranchCode { get; set; }

    public string CountryCode { get; set; }

    public string PlanId { get; set; }

    public System.DateTime subcriptionStart { get; set; }

    public System.DateTime subcriptionEnd { get; set; }

    public string status { get; set; }

}

}
