
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TemplateManagementSystem.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class TemplateCategory
{

    public int Id { get; set; }

    public Nullable<int> CategoryId { get; set; }

    public Nullable<int> TemplateId { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string CreatedBy { get; set; }



    public virtual Category Category { get; set; }

    public virtual SystemTemplate SystemTemplate { get; set; }

}

}
