
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TemplateManagementSystem.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Template5
{

    public int Id { get; set; }

    public string Name { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string Location { get; set; }

    public string CoordinatorName { get; set; }

    public string Activity { get; set; }

    public string NoOfLeaders { get; set; }

    public string RiskAnalysis { get; set; }

    public string CasualFactorPeople { get; set; }

    public string CasualFactorEquipment { get; set; }

    public string CasualFactorEnvironment { get; set; }

    public string NormalOperationPeople { get; set; }

    public string NormalOperationEquipment { get; set; }

    public string NormalOperationEnvironment { get; set; }

    public string EmergencyPeople { get; set; }

    public string EmergencyEquipment { get; set; }

    public string EmergencyEnvironment { get; set; }

    public string SkillsRequiredByLeaders { get; set; }

    public string FormCompletedBy { get; set; }

    public Nullable<System.DateTime> FormCompletionDate { get; set; }

    public Nullable<bool> ActivityStatus { get; set; }

    public string ApprovedBy { get; set; }

    public string Position { get; set; }

    public Nullable<System.DateTime> ApprovedDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public string FileName { get; set; }

}

}
