
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TemplateManagementSystem.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class TimeSheetDetail
{

    public int Id { get; set; }

    public Nullable<int> TimeSheetId { get; set; }

    public string JobDescription { get; set; }

    public Nullable<System.TimeSpan> TimeStarted { get; set; }

    public Nullable<System.TimeSpan> TimeStopped { get; set; }

    public string Initials { get; set; }



    public virtual DailyTimeSheet DailyTimeSheet { get; set; }

}

}
