
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TemplateManagementSystem.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class WashingTempletItem
{

    public int id { get; set; }

    public string item { get; set; }

    public string description { get; set; }

    public decimal price { get; set; }

    public int quantity { get; set; }

    public decimal ammount { get; set; }

    public Nullable<int> PressureWashingViewModel_Id { get; set; }



    public virtual PressureWashingViewModel PressureWashingViewModel { get; set; }

}

}
